/* AUTO-GENERATED FILE. DO NOT MODIFY. 
 *
  * This class was automatically generated by the
   * aapt tool from the resource data it found.  It
    * should not be modified by hand.
     */
     package com.qdefassist;

     public final class R {
     	public static final class color {
        		public static final int black = 1;
                		public static final int purple_200 = 0;
                        		public static final int purple_500 = 6;
                                		public static final int purple_700 = 5;
                                        		public static final int teal_200 = 2;
                                                		public static final int teal_700 = 4;
                                                        		public static final int white = 3;
                                                                	}
                                                                    	public static final class drawable {
                                                                        		public static final int ic_launcher_background = 8;
                                                                                		public static final int ic_launcher_foreground = 7;
                                                                                        	}
                                                                                            	public static final class layout {
                                                                                                		public static final int activity_main = 9;
                                                                                                        	}
                                                                                                            	public static final class mipmap {
                                                                                                                		public static final int ic_launcher = 21;
                                                                                                                        		public static final int ic_launcher_round = 15;
                                                                                                                                	}
                                                                                                                                    	public static final class string {
                                                                                                                                        		public static final int app_name = 22;
                                                                                                                                                	}
                                                                                                                                                    	public static final class style {
                                                                                                                                                        		public static final int Theme_MyApplication = 23;
                                                                                                                                                                	}
                                                                                                                                                                    }
                                                                                                                                                                    // Set the background color of a view
                                                                                                                                                                    myView.setBackgroundColor(getResources().getColor(R.color.purple_200));

                                                                                                                                                                    // Get a string resource
                                                                                                                                                                    String appName = getString(R.string.app_name);

                                                                                                                                                                    // Inflate a layout
                                                                                                                                                                    View myLayout = getLayoutInflater().inflate(R.layout.activity_main, parent, false);